services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  UBOS\Puckloader\:
    resource: '../Classes/*'
  UBOS\Puckloader\EventListener\DatabaseListener:
    tags:
      - name: event.listener
        identifier: 'puckloader/databaseListener'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

